-- Orhun 2026/2027 kvotalari — manba: 'EK 1. Annex 1 Quotas (1).xlsx' (Genel Tablo + 7 batafsil varaq)
-- scholarship_id=1, author_id=1, 87 universitet
START TRANSACTION;
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (125, 1, 10, 10, 10, 10, 'Fall/Spring 5/5 · Term: Fall and Spring · Dormitory: Yes (for female students) · Meals: Yes (2 meals a day)', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Baku Eurasian University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (127, 1, 5, 5, 5, 5, 'Term: Fall and Spring · Dormitory: Yes · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Azerbaijan State Pedagogical University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (18, 1, 0, 10, 30, 20, 'students out Fall/Spring 5/5; staff in Fall/Spring 15/15; staff out Fall/Spring 10/10 · Term: Fall and Spring · Dormitory: Guest house only for teaching staff · Meals: Not provided', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Azerbaijan State University of Economics (UNEC)
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (129, 1, 20, 20, 20, 6, 'students in Fall/Spring 10/10; students out Fall/Spring 10/10; staff in Fall/Spring 10/10; staff out Fall/Spring 3/3 · Term: Fall and Spring · Dormitory: Yes · Meals: Yes', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Baku Higher Oil School
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (16, 1, 10, 10, 10, 10, 'Fall/Spring 5/5 · Term: Fall and Spring · Dormitory: Öğretim üyeleri için misafirhane; Öğrenciler için yurt var · Meals: yalnız hafta içi sabah ve öğlen yemek imkanı var (tatil günleri ve haftasonu yoktur)', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Azerbaijan University of Architecture and Construc
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (19, 1, 10, 10, 10, 10, 'Fall/Spring 5/5 · Term: Fall and Spring · Dormitory: Yes · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Baku Slavic University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (14, 1, 10, 10, 0, 0, 'Term: Fall and Spring · Dormitory: Yes · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Baku State University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (25, 1, 20, 40, 20, 20, 'students in Fall/Spring 10/10; students out Fall/Spring 20/20; staff in Fall/Spring 10/10; staff out Fall/Spring 10/10 · Term: Fall and Spring · Dormitory: Misafir Evi · Meals: 2 meals a day available from Monday till Friday', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Mingachevir State University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (126, 1, 20, 10, 10, 10, 'students in Fall/Spring 10/10; students out Fall/Spring 5/5; staff in Fall/Spring 5/5; staff out Fall/Spring 5/5 · Term: Fall and Spring · Dormitory: No · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Azerbaijan State University of Culture and Arts
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (124, 1, 100, 40, 20, 10, 'students in Fall/Spring 50/50; students out Fall/Spring 20/20; staff in Fall/Spring 10/10; staff out Fall/Spring 5/5 · Term: Fall and Spring · Dormitory: Yes · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Lankaran State University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (130, 1, 20, 20, 20, 20, 'Fall/Spring 10/10 · Term: Fall and Spring · Dormitory: Yes · Meals: Yes', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Nakhchivan State University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (128, 1, 18, 18, 14, 14, 'students in Fall/Spring 9/9; students out Fall/Spring 9/9; staff in Fall/Spring 7/7; staff out Fall/Spring 7/7 · Term: Fall and Spring · Dormitory: No · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Azerbaijan Tourism and Management University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (132, 1, 30, 30, 20, 20, 'Term: Fall and Spring · Dormitory: For Students No For Staff Yes · Meals: Yes (1 meal (only lunch) a day)', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Azerbaijan Technical University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (17, 1, 4, 4, 4, 4, 'Term: Fall and Spring · Dormitory: (Please read the "additional information") · Meals: 2 meals (5 days a week)', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Azerbaijan University of Languages
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (21, 1, 4, 4, 4, 8, 'Term: Fall and Spring · Dormitory: Accomodation will be provided · Meals: Not available', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Azerbaijan Sport Academy
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (26, 1, 40, 40, 20, 20, 'Term: Fall and Spring · Dormitory: Yes, if places are available · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Al-Farabi Kazakh National University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (33, 1, 30, 30, 30, 30, 'Fall/Spring 15/15 · Term: Fall and Spring · Dormitory: Yes · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- K.Zhubanov Aktobe Regional University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (38, 1, 10, 10, 10, 10, 'Term: Fall and Spring · Dormitory: Yes · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Karaganda Buketov University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (39, 1, 5, 20, 5, 20, 'Term: Fall and Spring · Dormitory: yes · Meals: only breakfast', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Kyzylorda University named after Korkyt Ata
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (136, 1, 30, 30, 14, 14, 'students in Fall/Spring 30/0; students out Fall/Spring 10/20; staff in Fall/Spring 7/7; staff out Fall/Spring 7/7 · Term: Fall and Spring · Dormitory: Yes · Meals: 2 meals a day for academic staff', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Kazakh American Free University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (36, 1, 20, 20, 10, 10, 'students in Fall/Spring 10/10; students out Fall/Spring 10/10; staff in Fall/Spring 5/5; staff out Fall/Spring 5/5 · Term: Fall and Spring · Dormitory: No · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Almaty University of Management
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (28, 1, 150, 150, 50, 50, 'Term: Fall and Spring · Dormitory: Yes · Meals: 2 ÖĞÜN', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Akhmet Yassawi University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (30, 1, 10, 20, 20, 20, 'students in Fall/Spring 5/5; students out Fall/Spring 10/10; staff in Fall/Spring 10/10; staff out Fall/Spring 10/10 · Term: Fall and Spring · Dormitory: Yes · Meals: Yes', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Atyrau State University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (137, 1, 8, 8, 2, 2, 'students in Fall/Spring 4/4; students out Fall/Spring 4/4; staff in Fall/Spring 1/1; staff out Fall/Spring 1/1 · Term: Fall and Spring · Dormitory: Yes · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Kazakh National Academy of Choreography
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (40, 1, 20, 20, 8, 8, 'students in Fall/Spring 10/10; students out Fall/Spring 10/10; staff in Fall/Spring 4/4; staff out Fall/Spring 4/4 · Term: Fall and Spring · Dormitory: Dormitory is available only for students · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- International University of Tourism and Hospitalit
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (134, 1, 14, 20, 10, 10, 'students in Fall/Spring 7/7; students out Fall/Spring 10/10; staff in Fall/Spring 5/5; staff out Fall/Spring 5/5 · Term: Fall and Spring · Dormitory: Yes · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- East Kazakhstan Technical University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (27, 1, 40, 40, 20, 20, 'students in Fall/Spring 20/20; students out Fall/Spring 20/20; staff in Fall/Spring 10/10; staff out Fall/Spring 10/10 · Term: Fall and Spring · Dormitory: Accommodation for teachers is provided on a paid basis · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- L.N.Gumilyov Eurasian National University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (42, 1, 100, 40, 10, 10, 'students in Fall/Spring 50/50; students out Fall/Spring 20/20; staff in Fall/Spring 5/5; staff out Fall/Spring 5/5 · Term: Fall and Spring · Dormitory: please read additional information section) · Meals: please read additional information section)', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Doğu Akdeniz Üniversitesi (Cyprus)
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (8, 1, 4, 4, 3, 0, 'Term: Fall · Dormitory: Yes · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Arkin University of Creative Arts and Design
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (48, 1, 80, 80, 20, 40, 'students in Fall/Spring 40/40; students out Fall/Spring 40/40; staff in Fall/Spring 10/10; staff out Fall/Spring 20/20 · Term: Fall and Spring · Dormitory: Yes · Meals: Yes', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Kyrgyz-Turkish Manas University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (49, 1, 40, 60, 30, 30, 'students in Fall/Spring 20/20; students out Fall/Spring 30/30; staff in Fall/Spring 15/15; staff out Fall/Spring 15/15 · Term: Fall and Spring · Dormitory: Yes · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Osh State University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (45, 1, 40, 40, 20, 20, 'students in Fall/Spring 20/20; students out Fall/Spring 20/20; staff in Fall/Spring 10/10; staff out Fall/Spring 10/10 · Term: Fall and Spring · Dormitory: Yes · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Kyrgyz National University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (46, 1, 6, 60, 6, 10, 'students in Fall/Spring 3/3; students out Fall/Spring 30/30; staff in Fall/Spring 3/3; staff out Fall/Spring 5/5 · Term: Fall and Spring · Dormitory: Dormitory for studants,guest house for teachers,Yes · Meals: one meal a day (lunch),Yes', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Bishkek Humanities University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (47, 1, 20, 60, 20, 40, 'students in Fall/Spring 10/10; students out Fall/Spring 30/30; staff in Fall/Spring 10/10; staff out Fall/Spring 20/20 · Term: Fall and Spring · Dormitory: 1+1, 2+1 Daire · Meals: No meals are provided', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- International University of Kyrgyzstan
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (175, 1, 2, 2, 4, 4, 'students in Fall/Spring 1/1; students out Fall/Spring 1/1; staff in Fall/Spring 2/2; staff out Fall/Spring 2/2 · Term: Fall and Spring · Dormitory: No · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Szechenyi Istvan University of Györ
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (113, 1, 10, 10, 10, 10, 'Fall/Spring 5/5 · Term: Fall and Spring · Dormitory: Yes · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- University of World Economy and Diplomacy (UWED)
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (115, 1, 20, 10, 14, 14, 'students in Fall/Spring 10/10; students out Fall/Spring 5/5; staff in Fall/Spring 6/8; staff out Fall/Spring 6/8 · Term: Fall and Spring · Dormitory: Yes · Meals: 2 times a meal from Monday to Friday', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Kokand University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (4, 1, 4, 10, 4, 4, 'students in Fall/Spring 2/2; students out Fall/Spring 5/5; staff in Fall/Spring 2/2; staff out Fall/Spring 2/2 · Term: Fall and Spring · Dormitory: Yes · Meals: Five working days per week (Monday to Friday), excluding public holidays and non-working days', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Tashkent International University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (112, 1, 10, 6, 2, NULL, 'Term: Fall and Spring · Dormitory: Konaklama temin edilecekdir · Meals: Not available', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Tashkent State University of Uzbek language and li
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (117, 1, 3, 10, 3, 3, 'Term: Fall · Dormitory: Yes · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Journalism and Mass Communications University of t
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (120, 1, 40, 60, 10, 20, 'students in Fall/Spring 20/20; students out Fall/Spring 30/30; staff in Fall/Spring 5/5; staff out Fall/Spring 10/10 · Term: Fall and Spring · Dormitory: Yes · Meals: Yes', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Uzbekistan State Institute of Arts and Culture
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (119, 1, 10, 10, 20, 20, 'students in Fall/Spring 5/5; students out Fall/Spring 5/5; staff in Fall/Spring 10/10; staff out Fall/Spring 10/10 · Term: Fall and Spring · Dormitory: Yes · Meals: hospitaliy', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Samarkand State University named after Sharof Rash
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (114, 1, 3, 10, 3, 3, 'Term: Fall · Dormitory: Yes · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Tashkent State University of Oriental Studies
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (118, 1, 20, 31, 10, 5, 'Term: Fall and Spring · Dormitory: yes · Meals: no', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Tashkent State Transport University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (121, 1, 40, 40, 20, 20, 'students in Fall/Spring 20/20; students out Fall/Spring 20/20; staff in Fall/Spring 10/10; staff out Fall/Spring 10/10 · Term: Fall and Spring · Dormitory: Yes · Meals: On a contractual basis', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Termiz University of Economics and Service
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (92, 1, 20, 20, 40, 40, 'students in Fall/Spring 10/10; students out Fall/Spring 10/10; staff in Fall/Spring 20/20; staff out Fall/Spring 20/20 · Term: Fall and Spring · Dormitory: Paid) · Meals: 2 meals Evet', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Balıkesir Üniversitesi
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (86, 1, 20, 20, 10, 10, 'students in Fall/Spring 10/10; students out Fall/Spring 10/10; staff in Fall/Spring 5/5; staff out Fall/Spring 5/5 · Term: Fall and Spring · Dormitory: Yes · Meals: 2 Meals)', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Sakarya Üniversitesi
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (70, 1, 84, NULL, 63, NULL, 'Faculty-level breakdown: 38 programmes · Dormitory: Öğrenci için aylık yurt ücreti 2100 TL''dir. Personel için Konukevi günlük ücreti kahvaltı dahil 1200 TL''dir · Meals: Günlük kahvaltı ücreti 100 TL, yemek ücreti 145 TL''dir', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Erzincan Binali Yıldırım Üniversitesi
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (111, 1, 60, 40, 20, 20, 'students in Fall/Spring 30/30; students out Fall/Spring 20/20; staff in Fall/Spring 10/10; staff out Fall/Spring 10/10 · Term: Fall and Spring · Dormitory: Paylaşımlı Öğrenci evleri var, kira ücreri ödenmeyecek, sadece aylık elektrik, su, doğal gaz giderini öğrenci ödeyecek · Meals: Haftaiçi tek öğün yemek imkanı', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Firat Üniversitesi
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (58, 1, 10, 3, 5, 2, 'Term: Fall and Spring · Dormitory: Dormitory and guest house unavailable · Meals: 3 meals a day available', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Cappadocia University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (89, 1, 50, 50, 20, 20, 'students in Fall/Spring 25/25; students out Fall/Spring 25/25; staff in Fall/Spring 10/10; staff out Fall/Spring 10/10 · Term: Fall and Spring · Dormitory: No · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Iğdır Üniversitesi
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (55, 1, 5, 0, 0, 0, 'Term: Fall and Spring · Dormitory: Yes · Meals: 2 meals a day', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Eskisehir Osmangazi University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (74, 1, 10, 10, 10, 10, 'Fall/Spring 5/5 · Term: Fall and Spring · Dormitory: Yes, International GuestHouse · Meals: Yes, 2 Meals,Lunch and Dinner (From Monday Till Friday)', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Artvin Çoruh Ünıversitesi
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (81, 1, 10, 0, 0, 0, 'Faculty-level breakdown: 1 programmes', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Selçuk Üniversitesi
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (141, 1, 100, 100, 40, 40, 'students in Fall/Spring 50/50; students out Fall/Spring 50/50; staff in Fall/Spring 20/20; staff out Fall/Spring 20/20 · Term: Fall and Spring · Dormitory: No · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Karadeniz Technical University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (68, 1, 14, 14, 6, 6, 'Faculty-level breakdown: 3 programmes', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Anadolu University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (63, 1, 33, 33, 15, 15, 'Faculty-level breakdown: 6 programmes', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Kahramanmaraş Sütçüimam University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (52, 1, 167, 186, 205, 168, 'Faculty-level breakdown: 128 programmes', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Ege University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (97, 1, 3, 3, 4, 4, 'students in Fall term only; students out Spring term only; staff in Fall term only; staff out Spring term only · Term: Fall and Spring · Dormitory: Not available · Meals: Not available', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Kayseri Üniversitesi
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (144, 1, 4, 4, 4, 4, 'Fall/Spring 2/2 · Term: Fall and Spring · Dormitory: Yes · Meals: Yes', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Yozgat Bozok University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (150, 1, 3, 3, 0, 0, 'Term: Fall and Spring · Dormitory: No · Meals: Yes', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Adana Alparslan Türkeş Science and Technology Univ
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (94, 1, 20, 5, 5, 5, 'students in Fall/Spring 10/10; students out Fall/Spring 0/5; staff in Fall/Spring 2/3; staff out Fall/Spring 0/5 · Term: Fall and Spring · Dormitory: Evet (Yes) · Meals: Lunch)', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Ondokuz Mayıs Üniversitesi
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (64, 1, 5, 5, 3, 3, 'Term: Fall and Spring · Dormitory: Yes · Meals: Yes', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- İbn Haldun University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (71, 1, 10, 0, 7, 7, 'Term: Fall and Spring · Dormitory: (Please read the "additional information") · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Hacettepe Üniversitesi
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (96, 1, 10, 0, 10, 0, 'Fall/Spring 5/5 · Term: Fall and Spring · Dormitory: No · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Ankara Hacı Bayram Veli Üniversitesi
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (75, 1, 5, 5, 5, 5, 'Term: Fall and Spring · Dormitory: Yes · Meals: Sadece öğle yemeği', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Karamanoğlu Mehmetbey Üniversitesi
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (155, 1, 40, 20, 20, 20, 'students in Fall/Spring 20/20; students out Fall/Spring 10/10; staff in Fall/Spring 10/10; staff out Fall/Spring 10/10 · Term: Fall and Spring · Dormitory: No · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Bartın University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (100, 1, 30, 30, 20, 20, 'students in Fall/Spring 15/15; students out Fall/Spring 15/15; staff in Fall/Spring 10/10; staff out Fall/Spring 10/10 · Term: Fall and Spring · Dormitory: Not available · Meals: Lunch only on weekdays (University Hall)', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Kırklareli Üniversitesi
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (152, 1, 20, 20, 15, 15, 'students in Fall/Spring 10/10; students out Fall/Spring 10/10; staff in Fall/Spring 8/7; staff out Fall/Spring 8/7 · Term: Fall and Spring · Dormitory: Yes · Meals: Yes', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Muş Alparslan University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (106, 1, 22, 22, 4, 6, 'Faculty-level breakdown: 8 programmes', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- KTO-Karatay Üniversitesi
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (83, 1, 1, 0, 0, 0, 'Term: Spring · Dormitory: Yes · Meals: Yes', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Tokat Gaziosmanpaşa Üniversitesi
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (54, 1, 4, 4, 4, 4, 'Fall/Spring 2/2 · Term: Fall and Spring · Dormitory: Yes · Meals: Yes', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Bitlis Eren University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (82, 1, 0, 0, 1, 1, 'Term: Fall and Spring · Dormitory: Misafirhane Guest House · Meals: Yok No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Dokuz Eylül Üniversitesi
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (151, 1, 5, 5, 5, 5, 'Term: Fall and Spring · Dormitory: No · Meals: LUNCH (WEEKDAYS)', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Fatih Sultan Mehmet Vakıf University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (60, 1, 68, 69, 54, 54, 'Faculty-level breakdown: 26 programmes', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Alanya Alaaddin Keykubat Üniversitesi
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (148, 1, 0, 0, 0, 3, 'Term: Fall and Spring · Dormitory: No · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Van Yüzüncü Yıl University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (67, 1, 10, 0, 10, 0, 'Fall/Spring 5/5 · Term: Fall and Spring · Dormitory: VAR* (AVAILABLE) · Meals: ÖĞLE YEMEĞİ (HAFTA İÇİ) LUNCH (FROM MONDAY TİLL FRİDAY)', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Afyonkarahisar Sağlık Bilimleri University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (85, 1, 15, 15, 5, 5, 'students in Fall/Spring 8/7; students out Fall/Spring 8/7; staff in Fall/Spring 3/2; staff out Fall/Spring 3/2 · Term: Fall and Spring · Dormitory: yes · Meals: yes (every weekday)', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Ankara Müzik ve Güzel Sanatlar Üniversitesi
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (77, 1, 5, 5, 5, 5, 'Term: Fall and Spring · Dormitory: No · Meals: No', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Ankara Yıldırım Beyazıt Üniversitesi
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (53, 1, 8, 8, 8, 8, 'Fall/Spring 4/4 · Term: Fall and Spring · Dormitory: Yurt imkanı var · Meals: 1 Öğün Yemek', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Ataturk University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (62, 1, 20, 12, 20, 0, 'Term: Fall and Spring · Dormitory: Depending on the availability · Meals: Depending on the availability', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Bursa Uludağ Üniversitesi
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (140, 1, 0, 0, 4, 4, 'Term: Fall and Spring · Dormitory: No · Meals: 2 öğün yemek 5 gün', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Necmettin Erbakan University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (61, 1, 0, 0, 2, 2, 'Term: Fall and Spring · Dormitory: Yes · Meals: yalnız hafta içi öğlen yemek imkanı var (tatil günleri ve haftasonu yoktur)', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Ankara Üniversitesi
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (56, 1, 24, 20, 10, 10, 'students in Fall/Spring 12/12; students out Fall/Spring 10/10; staff in Fall/Spring 5/5; staff out Fall/Spring 5/5 · Term: Fall and Spring · Dormitory: Yes · Meals: Yes', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Nigde Omer Khalisdemir University
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (80, 1, 35, 20, 35, 20, 'Term: Fall and Spring · Dormitory: No · Meals: 1 ÖĞÜN', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Kastamonu Üniversitesi
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (109, 1, 15, 15, 20, 15, 'Term: Fall and Spring · Dormitory: Yes · Meals: Yes', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Istanbul Ticaret Üniversitesi
INSERT INTO orhun_quotas (member_id, scholarship_id, student_accept, student_send, teacher_accept, teacher_send, note, author_id, created_at, updated_at) VALUES (88, 1, 10, 10, 10, 10, 'Term: Fall and Spring · Dormitory: Yes · Meals: Depending on the Facilities within the University', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE student_accept=VALUES(student_accept), student_send=VALUES(student_send), teacher_accept=VALUES(teacher_accept), teacher_send=VALUES(teacher_send), note=VALUES(note), author_id=VALUES(author_id), updated_at=NOW();   -- Kırıkkale Üniversitesi
COMMIT;
